import type { Metadata } from "next";
import "./globals.css";

import { Poltawski_Nowy } from "@next/font/google";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Peerlist FormBuilder",
  description: "Generated by create next app",
};
const poltawskiNowy = Poltawski_Nowy({
  subsets: ["latin"], // Include specific subsets as needed
  weight: ["400", "700"], // Include weights you're using
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poltawskiNowy.className} antialiased`}>
        {children}
        <Toaster richColors/>
      </body>
    </html>
  );
}
