import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Peerlist FormBuilder",
  description: "Generated by create next app",
};

// Rename `Inter` to `interFont` to avoid conflicts
const interFont = Inter({
  subsets: ["latin"], // Include specific subsets as needed
  weight: ["400", "700"], // Include weights you're using
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.className} antialiased`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
